# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Michael Ian
email: michael@example.com
description: >-
  Bilingual marketing portfolio and creative showcase. 
  Canadian-born, China-experienced, culturally fluent.

twitter_username:
github_username: michael-ian
minimal_mistakes_skin: default
search: false

github_username: username
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Michael Ian"
  avatar : ""  # Add your own avatar image if you want (upload to /assets/images/)
  bio    : "Marketing | Bilingual Creator | Social Media Projects"
  links:
    - label: "Portfolio"
      icon: "fas fa-link"
      url: "https://michael-ian.github.io"
    - label: "Xiaohongshu"
      icon: "fab fa-redhat"
      url: "https://www.xiaohongshu.com/user/yourid"
    - label: "WeChat"
      icon: "fas fa-qrcode"
      url: "/assets/images/wechat-qr.png"  # upload your QR image

defaults:
  # _posts
  - scope:
      path: ""
    values:
      layout: single
      sidebar:
        nav: none
        show: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
