# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Arrest this man, he talks in maths
subtitle: Rodrigo Hernang贸mez's personal website
name: Rodrigo Hernang贸mez
email:
description: >- # this means to ignore newlines until "baseurl:"
  Rodrigo Hernang贸mez's personal website.
url: "https://rodrihgh.github.io"
repository: "rodrihgh/rodrihgh.github.io"
twitter_username: rodrihgh
github_username: rodrihgh
minimal_mistakes_skin: dirt
search: true

reCaptcha:
  enabled: true
  siteKey: "6LdF5uYUAAAAALPHJAys7PkiU7BiTJi-NRPTG9wm"
  secret: "KHMItsMBnmy+xppFbb2tRJvh3VL0F5dmPpsDPKfjWZE8wg2ZN54h3OepOD5G0PMiIz092LEHGzNc4kZjIZzfZZRd/qOlD+xsS6+rpvRmlM1gWf7xTvE1TxrbDmLz0vvKOWxcZ92fZJ5hmwrAwdmtt3H+2TECCkfvMs2yZkRydPg="

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Rodrigo Hernang贸mez"
  avatar : "/assets/images/bio-photo.png"
  bio    : "PhD student in Electrical Engineering. Fascinated by the interplay between beauty and math."
  location: raised in Madrid, based in Berlin
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/rodrigohgh/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/rodrihgh"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rodrihgh"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/rodrihgh"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/rodrigohgh/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/rodrihgh"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rodrihgh"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/rodrihgh"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
